const data = {
  products: [
    {
      name: 'productName',
      slug: 'productSlug1',
      category: 'productCat',
      image: '/images/img4.png',
      price: 2500,
      brand: 'productBrand',
      rating: 4.5,
      numReview: 10,
      description: 'prodcutDescrpt',
    },
    {
      name: 'productName',
      slug: 'productSlug2',
      category: 'productCat',
      image: 'images/img2.png',
      price: 2500,
      brand: 'productBrand',
      rating: 4.5,
      numReview: 10,
      description: 'prodcutDescrpt',
    },
    {
      name: 'productName',
      slug: 'productSlug3',
      category: 'productCat',
      image: 'images/img3.png',
      price: 2500,
      brand: 'productBrand',
      rating: 4.5,
      numReview: 10,
      description: 'prodcutDescrpt',
    },
    {
      name: 'productName',
      slug: 'productSlug4',
      category: 'productCat',
      image: 'images/img4.png',
      price: 2500,
      brand: 'productBrand',
      rating: 4.5,
      numReview: 10,
      description: 'prodcutDescrpt',
    },
  ],
};

export default data;
